id: P99CE8544
initial_creation_type: ocr
source_metadata:
  volumes:
    eaeab4cee2c34423a6f1916b38a73ff6:
      base_file: v089.txt
      image_group_id: I1PD95934
      title: འདུལ་བའི་མདོའི་འགྲེལ་པ་མངོན་པར་བརྗོད་པ་རང་གི་རྣམ་པར་བཤད་པ།
      total_pages: 1540
      volume_number: 89
